version: "3.9"
services:
  redis:
    image: redis:latest
    ports: 
      - 6379:6379
  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=vierkantewielen
      - MYSQL_USER=dami
      - MYSQL_PASSWORD=dami
