-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 11:04:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema vierkantewielen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vierkantewielen` DEFAULT CHARACTER SET utf8 ;
USE `vierkantewielen` ;

-- -----------------------------------------------------
-- Table `vierkantewielen`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vierkantewielen`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(64) NOT NULL,
  `infix` VARCHAR(24) NULL,
  `lastName` VARCHAR(64) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `gender` INT NULL,
  `permissionLevel` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isSick` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vierkantewielen`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vierkantewielen`.`subscriptions` (
  `startDate` DATE NOT NULL,
  `subscriptionLevel` INT NOT NULL,
  `lessonsUsed` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_subscription_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `vierkantewielen`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vierkantewielen`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vierkantewielen`.`cars` (
  `licencePlate` VARCHAR(32) NOT NULL,
  `manufacturers` VARCHAR(255) NULL,
  `color` VARCHAR(255) NULL,
  PRIMARY KEY (`licencePlate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vierkantewielen`.`Lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vierkantewielen`.`Lessons` (
  `lessonId` INT NOT NULL AUTO_INCREMENT,
  `lessonDate` DATE NOT NULL,
  `lessonDescription` TEXT(512) NULL,
  `isExam` TINYINT NULL,
  `isCanceled` TINYINT NULL,
  `car_licencePlate` VARCHAR(32) NOT NULL,
  `cancelReason` TEXT(512) NULL,
  `lessonGoal` TEXT(512) NULL,
  `ophaalLocatie` VARCHAR(255) NULL,
  PRIMARY KEY (`lessonId`, `car_licencePlate`),
  INDEX `fk_Lessons_car1_idx` (`car_licencePlate` ASC),
  CONSTRAINT `fk_Lessons_car1`
    FOREIGN KEY (`car_licencePlate`)
    REFERENCES `vierkantewielen`.`cars` (`licencePlate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vierkantewielen`.`UserLessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vierkantewielen`.`UserLessons` (
  `Lesson_lessonId` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`Lesson_lessonId`, `user_id`),
  INDEX `fk_Lessons_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_Lessons_has_user_Lessons1_idx` (`Lesson_lessonId` ASC),
  CONSTRAINT `fk_Lessons_has_user_Lessons1`
    FOREIGN KEY (`Lesson_lessonId`)
    REFERENCES `vierkantewielen`.`Lessons` (`lessonId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lessons_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vierkantewielen`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vierkantewielen`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vierkantewielen`.`notes` (
  `note` TEXT(512) NOT NULL,
  `Lesson_lessonId` INT NOT NULL,
  PRIMARY KEY (`Lesson_lessonId`),
  CONSTRAINT `fk_notes_Lessons1`
    FOREIGN KEY (`Lesson_lessonId`)
    REFERENCES `vierkantewielen`.`Lessons` (`lessonId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vierkantewielen`.`announcments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vierkantewielen`.`announcments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` TEXT(1028) NULL,
  `footer` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vierkantewielen`.`userAnnouncements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vierkantewielen`.`userAnnouncements` (
  `user_id` INT NOT NULL,
  `announcment_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `announcment_id`),
  INDEX `fk_user_has_announcment_announcment1_idx` (`announcment_id` ASC),
  INDEX `fk_user_has_announcment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_announcment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vierkantewielen`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_announcment_announcment1`
    FOREIGN KEY (`announcment_id`)
    REFERENCES `vierkantewielen`.`announcments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vierkantewielen`.`results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vierkantewielen`.`results` (
  `result` VARCHAR(255) NULL,
  `positive` TEXT(512) NULL,
  `negative` TEXT(512) NULL,
  `Lessons_lessonId` INT NOT NULL,
  PRIMARY KEY (`Lessons_lessonId`),
  CONSTRAINT `fk_result_Lessons1`
    FOREIGN KEY (`Lessons_lessonId`)
    REFERENCES `vierkantewielen`.`Lessons` (`lessonId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
